version: '3.8'
services:
  react-app:
    container_name: react-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  react-app-test:
    container_name: react-app-test-container
    build:
      context: .
      dockerfile: Dockerfile.test-coverage
    ports:
      - "8080:8080"
