# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle app source
COPY . .

# Build the app
RUN npm run test

# Install serve to run the application
RUN npm install -g http-server

WORKDIR /usr/src/app/coverage/lcov-report

EXPOSE 8080

# Run the app
CMD ["http-server", "."]